import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Poppins } from "next/font/google"

// Components
import Layout from './components/layout-main/Layout'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Raditya's Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${poppins.className}`}>
        <Layout>
          <section>
            This is for Raditya Introduction
          </section>
          <section>
            This is About section
          </section>
          <section>
            This is Experience section
          </section>
          <section>
            This is To do list section
          </section>
          <section>
            Other
          </section>
          <section>
            Other
          </section>
          <section>
            Other
          </section>
          <section>
            Other
          </section>
        </Layout>
      </main>
    </>
  )
}
